schema_name: config_schema_rh
tactic: limit
num_of_imgs: 25
repeat_every: '0 0 * * *'
apps: all
robots: all
target_dataset:
  team_id: luxonis_id
  team_name: luxonis_team
  dataset_name: new_robothub_dataset
