import colorsys
import hashlib
import math
from collections import defaultdict
from collections.abc import Generator, Hashable, Iterator, Mapping

import cv2
import matplotlib.colors
import numpy as np
from bidict import bidict

from luxonis_ml.data.utils import (
    get_task_name,
    get_task_type,
    task_type_iterator,
)
from luxonis_ml.typing import HSV, RGB, Annotations, Color

FONT = cv2.FONT_HERSHEY_SIMPLEX
MAX_METADATA_VALUE_LENGTH = 120


class ColorMap(Mapping[Hashable, RGB]):
    """A mapping that assigns distinct RGB colors to hashable keys.

    `ColorMap` generates and stores distinct colors for arbitrary
    hashable keys. Colors are lazily assigned on request using
    `distinct_color_generator`.
    """

    def __init__(self):
        self._generator = distinct_color_generator()
        self._color_dict: dict[Hashable, RGB] = {}

    def __getitem__(self, label: Hashable) -> RGB:
        if label not in self._color_dict:
            self._color_dict[label] = next(self._generator)
        return self._color_dict[label]

    def __iter__(self) -> Iterator[Hashable]:
        return iter(self._color_dict)

    def __len__(self) -> int:
        return len(self._color_dict)


def distinct_color_generator(stop: int = -1) -> Generator[RGB, None, None]:
    r"""Generate distinct RGB colors using the golden ratio.

    This generator produces a sequence of distinct colors in RGB format.
    The colors are generated by incrementing the hue by the golden ratio
    and keeping saturation and value fixed. This ensures a wide
    distribution of visually distinct colors.

    Args:
        stop: optional maximum number of colors to generate. If set to
            :math:`-1`, the generator continues indefinitely.

    Yields:
        The next RGB color with each component in the range
        :math:`\left[0, 255\right]`.

    Examples:
        >>> colors = list(distinct_color_generator(stop=2))
        >>> len(colors)
        2
        >>> all(len(color) == 3 for color in colors)
        True

    """
    golden_ratio = 0.618033988749895
    hue = 0.0
    i = 0
    while True:
        if i == stop:
            break
        hue = (hue + golden_ratio) % 1
        saturation = 0.8
        value = 0.95
        r, g, b = colorsys.hsv_to_rgb(hue, saturation, value)
        yield int(r * 255), int(g * 255), int(b * 255)
        i += 1


def resolve_color(color: Color) -> RGB:
    r"""Resolve a color to RGB.

    Args:
        color: Color to resolve.

    Returns:
        The resolved RGB color.

    Raises:
        ValueError: If an integer channel value is outside
            :math:`\left[0, 255\right]`.

    Examples:
        >>> resolve_color(12)
        (12, 12, 12)
        >>> resolve_color((1, 2, 3))
        (1, 2, 3)
        >>> resolve_color(300)
        Traceback (most recent call last):
        ...
        ValueError: Color value 300 is out of range [0, 255]

    """

    def _check_range(val: int) -> None:
        if val < 0 or val > 255:
            raise ValueError(f"Color value {val} is out of range [0, 255]")

    if isinstance(color, str):
        return matplotlib.colors.to_rgb(color)  # type: ignore
    if isinstance(color, int):
        _check_range(color)
        return color, color, color
    for c in color:
        _check_range(c)
    return color


def rgb_to_hsv(color: Color) -> HSV:
    r"""Convert an RGB color to HSV.

    Args:
        color: Color to convert.

    Returns:
        The converted HSV color.

    Examples:
        >>> tuple(round(v, 3) for v in rgb_to_hsv((255, 0, 0)))
        (0.0, 1.0, 1.0)
        >>> tuple(round(v, 3) for v in rgb_to_hsv(128))
        (0.0, 0.0, 0.502)

    """
    r, g, b = resolve_color(color)
    h, s, br = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
    return h * 360, s, br


def hsv_to_rgb(color: HSV) -> RGB:
    """Convert an HSV color to RGB.

    Args:
        color: HSV color to convert.

    Returns:
        The converted RGB color.

    Examples:
        >>> hsv_to_rgb((0, 1, 1))
        (255, 0, 0)
        >>> hsv_to_rgb((120, 1, 1))
        (0, 255, 0)

    """
    h, s, b = color
    r, g, b = colorsys.hsv_to_rgb(h / 360, s, b)
    return int(r * 255), int(g * 255), int(b * 255)


def get_contrast_color(color: Color) -> RGB:
    """Return a contrasting color for the given RGB color.

    Args:
        color: Color to contrast.

    Returns:
        The contrasting color.

    Examples:
        >>> get_contrast_color((255, 0, 0))
        (0, 255, 255)
        >>> get_contrast_color(0)
        (0, 0, 0)

    """
    h, s, v = rgb_to_hsv(resolve_color(color))
    h = (h + 180) % 360
    return hsv_to_rgb((h, s, v))


def str_to_rgb(string: str) -> RGB:
    """Convert a string to its deterministic RGB color.

    Args:
        string: String to convert.

    Returns:
        Deterministic RGB color.

    Examples:
        >>> str_to_rgb("car") == str_to_rgb("car")
        True
        >>> len(str_to_rgb("car"))
        3

    Returns:
        The generated RGB color.

    """
    h = int(hashlib.md5(string.encode()).hexdigest(), 16)  # noqa: S324
    r = (h & 0xFF0000) >> 16
    g = (h & 0x00FF00) >> 8
    b = h & 0x0000FF

    return r, g, b


def draw_dashed_rectangle(
    image: np.ndarray,
    pt1: tuple[int, int],
    pt2: tuple[int, int],
    color: Color,
    thickness: int = 1,
    dash_length: int = 10,
) -> None:
    """Draw a dashed rectangle on the image.

    Args:
        image: Image to draw on.
        pt1: Top-left corner of the rectangle.
        pt2: Bottom-right corner of the rectangle.
        color: Rectangle color.
        thickness: Line thickness.
        dash_length: Length of each dash.

    """
    x1, y1 = pt1
    x2, y2 = pt2

    def draw_dashed_line(p1: tuple[int, int], p2: tuple[int, int]) -> None:
        line_length = int(np.hypot(p2[0] - p1[0], p2[1] - p1[1]))
        dashes = [
            (i, i + dash_length)
            for i in range(0, line_length, 2 * dash_length)
        ]
        for start, end in dashes:
            end = min(end, line_length)
            start_point = (
                int(p1[0] + (p2[0] - p1[0]) * start / line_length),
                int(p1[1] + (p2[1] - p1[1]) * start / line_length),
            )
            end_point = (
                int(p1[0] + (p2[0] - p1[0]) * end / line_length),
                int(p1[1] + (p2[1] - p1[1]) * end / line_length),
            )
            cv2.line(
                image, start_point, end_point, resolve_color(color), thickness
            )

    draw_dashed_line((x1, y1), (x2, y1))
    draw_dashed_line((x2, y1), (x2, y2))
    draw_dashed_line((x2, y2), (x1, y2))
    draw_dashed_line((x1, y2), (x1, y1))


def draw_cross(
    img: np.ndarray,
    center: tuple[int, int],
    size: int = 5,
    color: Color = 0,
    thickness: int = 1,
) -> None:
    """Draw a cross on the image.

    Args:
        img: Image to draw on.
        center: Center of the cross.
        size: Size of the cross.
        color: Cross color.
        thickness: Line thickness.

    """
    x, y = center
    color = resolve_color(color)
    cv2.line(img, (x - size, y), (x + size, y), color, thickness)
    cv2.line(img, (x, y - size), (x, y + size), color, thickness)


def create_text_image(
    text: str,
    width: int,
    height: int,
    font_size: float = 0.7,
    bg_color: Color = 255,
    text_color: Color = 0,
) -> np.ndarray:
    """Create an image with centered text.

    Args:
        text: Text to display.
        width: Image width.
        height: Image height.
        font_size: Font size for the text.
        bg_color: Background color.
        text_color: Text color.

    Returns:
        The generated image.

    """
    img = np.full((height, width, 3), resolve_color(bg_color), dtype=np.uint8)

    text_size = cv2.getTextSize(text, FONT, font_size, 1)[0]

    text_x = (width - text_size[0]) // 2
    text_y = (height + text_size[1]) // 2

    cv2.putText(
        img,
        text,
        (text_x, text_y),
        fontFace=FONT,
        fontScale=font_size,
        color=resolve_color(text_color),
        thickness=1,
        lineType=cv2.LINE_AA,
    )

    return img


def concat_images(
    image_dict: dict[str, np.ndarray],
    padding: int = 10,
    label_height: int = 30,
) -> np.ndarray:
    """Concatenate images into a single labeled image.

    It will attempt to create a square grid of images.

    Args:
        image_dict: Mapping of image names to images.
        padding: Padding between images.
        label_height: Height of each label.

    Returns:
        The concatenated image.

    """
    n_images = len(image_dict)
    n_cols = math.ceil(math.sqrt(n_images))
    n_rows = math.ceil(n_images / n_cols)

    max_h = max(img.shape[0] for img in image_dict.values())
    max_w = max(img.shape[1] for img in image_dict.values())

    cell_height = max_h + 2 * padding + label_height
    cell_width = max_w + 2 * padding

    output = np.full(
        (cell_height * n_rows, cell_width * n_cols, 3), 255, dtype=np.uint8
    )

    for idx, (name, img) in enumerate(image_dict.items()):
        i = idx // n_cols
        j = idx % n_cols

        y_start = i * cell_height
        x_start = j * cell_width

        label = create_text_image(name, cell_width, label_height)
        output[
            y_start : y_start + label_height, x_start : x_start + cell_width
        ] = label

        h, w = img.shape[:2]
        y_img = y_start + label_height + padding
        x_img = x_start + padding
        output[y_img : y_img + h, x_img : x_img + w] = img

    return output


def append_text_block(
    image: np.ndarray,
    lines: list[str],
    font_scale: float,
    bg_color: Color = (245, 245, 245),
    text_color: Color = (32, 32, 32),
) -> np.ndarray:
    """Append a multi-line text block below the image."""
    if not lines:
        return image

    font_scale = max(0.4, font_scale)
    padding_x = max(10, round(18 * font_scale))
    padding_y = max(8, round(14 * font_scale))
    line_spacing = max(6, round(8 * font_scale))
    thickness = 1
    max_text_width = image.shape[1] - 2 * padding_x

    wrapped_lines: list[str] = []
    for line in lines:
        wrapped_lines.extend(wrap_text(line, max_text_width, font_scale))

    if not wrapped_lines:
        return image

    (_, text_height), baseline = cv2.getTextSize(
        "Ag", FONT, font_scale, thickness
    )
    footer_height = (
        2 * padding_y
        + len(wrapped_lines) * text_height
        + max(0, len(wrapped_lines) - 1) * line_spacing
        + baseline
    )

    footer = np.full(
        (footer_height, image.shape[1], 3),
        resolve_color(bg_color),
        dtype=np.uint8,
    )
    cv2.line(
        footer,
        (0, 0),
        (footer.shape[1], 0),
        resolve_color((210, 210, 210)),
        1,
    )

    y = padding_y + text_height
    for line in wrapped_lines:
        cv2.putText(
            footer,
            line,
            (padding_x, y),
            FONT,
            font_scale,
            resolve_color(text_color),
            thickness,
            cv2.LINE_AA,
        )
        y += text_height + line_spacing

    return np.vstack((image, footer))


def add_augmentation_footer(
    image: np.ndarray, augmentations: list[str]
) -> np.ndarray:
    """Append the applied augmentations as a footer below the image."""
    min_dimension = min(image.shape[:2])
    font_scale = max(0.25, min(1.1, 0.4 * min_dimension / 500))
    augmentations_text = ", ".join(augmentations) if augmentations else "none"
    return append_text_block(
        image,
        [f"Augmentations: {augmentations_text}"],
        font_scale=font_scale,
    )


def wrap_text(
    text: str,
    max_width: int,
    font_scale: float,
    thickness: int = 1,
) -> list[str]:
    """Wrap text into lines that fit within the given width."""
    if max_width <= 0:
        return [text]

    words = text.split()
    if not words:
        return [""]

    lines: list[str] = []
    current_line = words[0]

    for word in words[1:]:
        candidate = f"{current_line} {word}"
        candidate_width = cv2.getTextSize(
            candidate, FONT, font_scale, thickness
        )[0][0]
        if candidate_width <= max_width:
            current_line = candidate
        else:
            lines.append(current_line)
            current_line = word

    lines.append(current_line)
    return lines


def draw_bbox_label(
    image: np.ndarray,
    class_name: str,
    box: np.ndarray,
    color: tuple[int, int, int],
    font_scale: float,
) -> None:
    """Draw the class name label at the top-left corner of the bounding
    box.

    Args:
        image: Image to draw on.
        class_name: Name of the class.
        box: Bounding box coordinates in ``[class_id, x1, y1, x2, y2]``
            format, where ``(x1, y1)`` is the top-left corner and
            ``(x2, y2)`` is the bottom-right corner.
        color: Label color.
        font_scale: Font scale.

    """
    text = class_name

    text_size = cv2.getTextSize(text, FONT, font_scale, 1)[0]
    text_x = box[1]
    text_y = max(box[2] - 5, text_size[1])

    cv2.rectangle(
        image,
        (text_x - 2, text_y - text_size[1] - 2),
        (text_x + text_size[0] + 2, text_y + 2),
        color,
        -1,
    )
    cv2.putText(
        image,
        text,
        (text_x, text_y),
        FONT,
        font_scale,
        (255, 255, 255),
        1,
        cv2.LINE_AA,
    )


def draw_keypoint_label(
    image: np.ndarray,
    text: str,
    point: tuple[int, int],
    size: int,
    color: tuple[int, int, int],
    font_scale: float,
) -> None:
    """Draw a text label next to a keypoint on the image.

    Args:
        image: Image to draw on.
        text: Text to draw.
        point: Keypoint coordinates.
        size: Keypoint size.
        color: Text color.
        font_scale: Font scale.

    """
    text_size = cv2.getTextSize(text, FONT, font_scale, 1)[0]
    text_x = point[0] + size + 2
    text_y = point[1] + text_size[1] // 2

    cv2.putText(
        image,
        text,
        (text_x, text_y),
        FONT,
        font_scale,
        color,
        1,
        cv2.LINE_AA,
    )


def visualize(
    image: np.ndarray,
    source_name: str,
    annotations: Annotations,
    classes: dict[str, dict[str, int]],
    blend_all: bool = False,
    categorical_encodings: dict[str, dict[str, int]] | None = None,
    metadata: Mapping[str, object] | None = None,
) -> np.ndarray:
    """Visualize annotations on an image.

    Args:
        image: Image to visualize.
        source_name: Name of the image source.
        annotations: Annotations to visualize.
        classes: Mapping from task names to class ID mappings.
        blend_all: Whether to blend all annotations, except semantic
            segmentations, into a single image. This mixes annotations that
            belong to different tasks.
        categorical_encodings: Optional mapping for categorical custom labels.
            Keys are full task identifiers such as
            ``"{task_name}/labels/{key}"`` and values map string labels to
            encoded integers.
        metadata: Optional record metadata to append under the rendered
            labels.

    Returns:
        The visualized image.

    """
    h, w, _ = image.shape
    images = {source_name: image}
    mappings = {task: bidict(c) for task, c in classes.items()}
    custom_labels_mappings = {
        task: bidict(encoding)
        for task, encoding in (categorical_encodings or {}).items()
    }

    min_dimension = min(h, w)
    font_scale = max(0.25, min(1.1, 0.4 * min_dimension / 500))
    small_kp_size = max(2, round(0.002 * min_dimension))
    large_kp_size = max(4, round(0.004 * min_dimension))

    def create_mask(
        image: np.ndarray, arr: np.ndarray, task_name: str, is_instance: bool
    ) -> np.ndarray:
        mask_viz = np.zeros((h, w, 3)).astype(np.uint8)
        for i, mask in enumerate(arr):
            mask = cv2.resize(mask, (w, h), interpolation=cv2.INTER_NEAREST)
            if is_instance:
                task_classes = mappings[task_name]
                if len(bbox_classes[task_name]) > i:
                    class_id = bbox_classes[task_name][i]
                    color = str_to_rgb(task_classes.inverse[class_id])
                else:
                    color = (255, 0, 0)
                mask_viz[mask > 0] = color
            else:
                mask_viz[mask == 1] = (
                    str_to_rgb(mappings[task_name].inverse[i])
                    if (i != 0 or len(arr) == 1)
                    else (0, 0, 0)
                )

        binary_mask = (mask_viz > 0).astype(np.uint8)

        return np.where(
            binary_mask > 0,
            cv2.addWeighted(image, 0.4, mask_viz, 0.6, 0),
            image,
        )

    bbox_classes = defaultdict(list)
    classification_annotations: list[tuple[str, list[str]]] = []
    custom_labels: list[tuple[str, list[str]]] = []

    def format_label_value(task: str, value: object) -> str:
        if isinstance(value, np.generic):
            value = value.item()

        if task in custom_labels_mappings and isinstance(
            value, (int, str, bytes, bytearray)
        ):
            try:
                return custom_labels_mappings[task].inverse[int(value)]
            except (KeyError, ValueError):
                pass

        if isinstance(value, float):
            return f"{value:g}"
        return str(value)

    def truncate_metadata_value(value: str) -> str:
        if len(value) <= MAX_METADATA_VALUE_LENGTH:
            return value
        return f"{value[: MAX_METADATA_VALUE_LENGTH - 3]}..."

    def format_metadata_value(value: object) -> str:
        if isinstance(value, np.generic):
            value = value.item()

        if isinstance(value, Mapping):
            return truncate_metadata_value(
                ", ".join(
                    f"{key}: {format_metadata_value(nested_value)}"
                    for key, nested_value in value.items()
                )
            )

        if isinstance(value, (list, tuple, set)):
            return truncate_metadata_value(
                ", ".join(format_metadata_value(item) for item in value)
            )

        if isinstance(value, float):
            return f"{value:g}"
        return truncate_metadata_value(str(value))

    def format_augmentation_source(source: object) -> str:
        if not isinstance(source, Mapping):
            return format_metadata_value(source)

        role = source.get("role", "source")
        input_index = source.get("input_index", "?")
        source_metadata = source.get("metadata", {})
        return truncate_metadata_value(
            f"{role}[{input_index}]: {format_metadata_value(source_metadata)}"
        )

    def format_metadata_lines(metadata: Mapping[str, object]) -> list[str]:
        lines = ["Metadata:"]
        for key, value in metadata.items():
            if key == "augmentation_sources" and isinstance(
                value, (list, tuple)
            ):
                lines.append("augmentation_sources:")
                lines.extend(
                    format_augmentation_source(source) for source in value
                )
                continue

            lines.append(f"{key}: {format_metadata_value(value)}")
        return lines

    for task, arr in task_type_iterator(annotations, "segmentation"):
        task_name = get_task_name(task)
        image_name = (
            task_name if task_name and not blend_all else "annotations"
        )
        images[image_name] = create_mask(
            image, arr, task_name, is_instance=False
        )

    for task, arr in task_type_iterator(annotations, "boundingbox"):
        task_name = get_task_name(task)
        image_name = (
            task_name if task_name and not blend_all else "annotations"
        )
        curr_image = images.get(image_name, image.copy())

        draw_function = cv2.rectangle

        is_sublabel = len(task.split("/")) > 2

        if is_sublabel:
            draw_function = draw_dashed_rectangle

        arr[:, [1, 3]] *= w
        arr[:, [2, 4]] *= h
        arr[:, 3] += arr[:, 1]
        arr[:, 4] += arr[:, 2]
        arr = arr.astype(int)

        for box in arr:
            class_id = int(box[0])
            bbox_classes[task_name].append(class_id)
            class_name = mappings[task_name].inverse[class_id]
            color = str_to_rgb(class_name)
            draw_function(
                curr_image,
                (box[1], box[2]),
                (box[3], box[4]),
                color,
                thickness=2,
            )
            draw_bbox_label(curr_image, class_name, box, color, font_scale)
        images[image_name] = curr_image

    for task, arr in task_type_iterator(annotations, "instance_segmentation"):
        task_name = get_task_name(task)
        image_name = (
            task_name if task_name and not blend_all else "annotations"
        )
        curr_image = images.get(image_name, image.copy())
        images[image_name] = create_mask(
            curr_image, arr, task_name, is_instance=True
        )

    for task, arr in task_type_iterator(annotations, "classification"):
        task_name = get_task_name(task)
        task_classes = mappings.get(task_name)
        if task_classes is None:
            continue

        class_ids = np.flatnonzero(np.asarray(arr).reshape(-1) > 0)
        if len(class_ids) == 0:
            continue

        class_names = [
            task_classes.inverse[int(class_id)] for class_id in class_ids
        ]
        classification_annotations.append((task_name, class_names))

    for task, arr in annotations.items():
        task_type = get_task_type(task)
        if not task_type.startswith("labels/"):
            continue

        label_name = task_type.removeprefix("labels/")
        task_name = get_task_name(task)
        label_name = f"{task_name}/{label_name}" if task_name else label_name
        values = np.asarray(arr).reshape(-1)
        if len(values) == 0:
            continue

        formatted_values = [
            format_label_value(task, value) for value in values
        ]
        unique_values = list(dict.fromkeys(formatted_values))
        custom_labels.append((label_name, unique_values))

    for task, arr in task_type_iterator(annotations, "keypoints"):
        task_name = get_task_name(task)
        image_name = (
            task_name if task_name and not blend_all else "annotations"
        )
        curr_image = images.get(image_name, image.copy())

        task_classes = mappings[task_name]

        for i, kp in enumerate(arr):
            kp = kp.reshape(-1, 3)
            if len(bbox_classes[task_name]) > i:
                class_id = bbox_classes[task_name][i]
                color = get_contrast_color(
                    str_to_rgb(task_classes.inverse[class_id])
                )
            else:
                color = (255, 0, 0)
            for j, k in enumerate(kp):
                visibility = int(k[-1])
                if visibility == 0:
                    continue

                if visibility == 2:
                    draw_function = cv2.circle
                    size = small_kp_size
                else:
                    draw_function = draw_cross
                    size = large_kp_size

                point = (int(k[0] * w), int(k[1] * h))
                draw_function(
                    curr_image,
                    point,
                    size,
                    color=color,
                    thickness=2,
                )

                text = str(j)
                draw_keypoint_label(
                    curr_image, text, point, size, color, font_scale
                )

        images[image_name] = curr_image

    output = concat_images(images)

    text_lines: list[str] = []
    if len(classification_annotations) == 1:
        _, class_names = classification_annotations[0]
        text_lines.extend(["Classes:", ", ".join(class_names)])
    elif classification_annotations:
        text_lines.extend(
            ["Classification annotations:"]
            + [
                f"{task_name}: {', '.join(class_names)}"
                for task_name, class_names in classification_annotations
            ]
        )

    if custom_labels:
        text_lines.extend(
            ["Custom labels:"]
            + [
                f"{label_name}: {', '.join(values)}"
                for label_name, values in custom_labels
            ]
        )

    if metadata:
        text_lines.extend(format_metadata_lines(metadata))

    if text_lines:
        output = append_text_block(output, text_lines, font_scale)

    return output
