#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Keep the lockfile and the pip compatibility exports in sync with pyproject.toml.
uv lock

export_requirements() {
  local output_file="$1"
  shift

  {
    echo '# This file is autogenerated by uv. Do not edit it manually.'
    echo '# Add or update dependencies in pyproject.toml, then run scripts/export_requirements.sh.'
    # `opencv-python-headless` is overridden to an unsatisfiable marker in
    # pyproject.toml, so it never installs; skip emitting the dead entry.
    uv export --locked --format requirements.txt --no-header \
      --no-annotate --no-emit-project \
      --no-emit-package opencv-python-headless "$@"
  } >"$output_file"
}

export_requirements requirements.txt --no-default-groups
export_requirements requirements-all.txt --no-default-groups --all-extras
export_requirements requirements-dev.txt --no-default-groups --group dev
