#!/usr/bin/env bash

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

# Keep the lockfile and pip compatibility exports in sync with pyproject.toml.
uv lock

export_requirements() {
  local output_file="$1"
  shift

  local temporary_file
  temporary_file="$(mktemp "${output_file}.XXXXXX")"

  if ! {
    printf '%s\n' '# This file is autogenerated by uv. Do not edit it manually.'
    printf '%s\n' '# Add or update dependencies in pyproject.toml, then run scripts/export_requirements.sh.'
    uv export --locked --format requirements.txt --no-header --no-annotate \
      --no-hashes --no-emit-project "$@"
  } >"$temporary_file"; then
    rm -f "$temporary_file"
    return 1
  fi

  mv "$temporary_file" "$output_file"
}

export_requirements requirements.txt --no-default-groups
export_requirements requirements-dev.txt --no-default-groups --extra dev
export_requirements luxonis_ml/data/requirements.txt --no-default-groups --extra data
export_requirements luxonis_ml/utils/requirements.txt --no-default-groups
export_requirements luxonis_ml/tracker/requirements.txt --no-default-groups --extra tracker
export_requirements luxonis_ml/nn_archive/requirements.txt --no-default-groups --extra nn_archive
export_requirements extra_requirements/gcs.txt --no-default-groups --extra gcs
export_requirements extra_requirements/mlflow.txt --no-default-groups --extra mlflow
export_requirements extra_requirements/posthog.txt --no-default-groups --extra telemetry
export_requirements extra_requirements/roboflow.txt --no-default-groups --extra roboflow
export_requirements extra_requirements/s3.txt --no-default-groups --extra s3
