#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Keep the lockfile and the pip compatibility exports in sync with pyproject.toml.
uv lock

export_requirements() {
  local output="$1"
  shift

  local tmp
  tmp="$(mktemp "${output}.XXXXXX")"

  if ! {
    printf '%s\n' '# This file is autogenerated by uv. Do not edit it manually.'
    printf '%s\n' '# Add or update dependencies in pyproject.toml, then run tools/export_requirements.sh.'
    # `opencv-python-headless` is overridden to an unsatisfiable marker in
    # pyproject.toml, so it never installs; skip emitting the dead entry.
    uv export --locked --format requirements.txt --no-header \
      --no-annotate --no-emit-project \
      --no-emit-package opencv-python-headless "$@"
  } >"$tmp"; then
    rm -f "$tmp"
    return 1
  fi

  mv "$tmp" "$output"
}

export_requirements requirements.txt --no-default-groups

# Keep the compatibility exports unhashed, as they were before the uv migration.
# This is required for `data`: pip restores `opencv-python-headless`, which uv
# overrides out of the lock, and hash mode rejects that unlisted dependency.
unhashed=(--no-hashes --no-default-groups)
export_requirements requirements-all.txt "${unhashed[@]}" --all-extras
export_requirements requirements-dev.txt "${unhashed[@]}" --group dev
export_requirements luxonis_ml/data/requirements.txt "${unhashed[@]}" --extra data
export_requirements luxonis_ml/nn_archive/requirements.txt "${unhashed[@]}" --extra nn_archive
export_requirements luxonis_ml/tracker/requirements.txt "${unhashed[@]}" --extra tracker
export_requirements luxonis_ml/utils/requirements.txt "${unhashed[@]}" --extra utils

mkdir -p extra_requirements
export_requirements extra_requirements/gcs.txt "${unhashed[@]}" --extra gcs
export_requirements extra_requirements/mlflow.txt "${unhashed[@]}" --extra mlflow
export_requirements extra_requirements/posthog.txt "${unhashed[@]}" --extra telemetry
export_requirements extra_requirements/roboflow.txt "${unhashed[@]}" --extra roboflow
export_requirements extra_requirements/s3.txt "${unhashed[@]}" --extra s3
