#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Keep the lockfile and the pip compatibility exports in sync with pyproject.toml.
uv lock

export_requirements() {
  local output_file="$1"
  shift

  {
    echo '# This file is autogenerated by uv. Do not edit it manually.'
    echo '# Add or update dependencies in pyproject.toml, then run tools/export_requirements.sh.'
    # `opencv-python-headless` is overridden to an unsatisfiable marker in
    # pyproject.toml, so it never installs; skip emitting the dead entry.
    uv export --locked --format requirements.txt --no-header \
      --no-annotate --no-emit-project \
      --no-emit-package opencv-python-headless "$@"
  } >"$output_file"
}

export_requirements requirements.txt --no-default-groups

# The exports that pull in the `data` extra cannot carry hashes. `albucore`
# requires `opencv-python-headless`, which the `[tool.uv]` override drops from
# the resolution. pip does not honour that override, so it resolves the
# dependency itself and then rejects the whole file, because `--require-hashes`
# mode demands that every requirement be pinned in it. Version pins without
# hashes keep these files installable, and pip users end up with the same
# `opencv-python-headless` that `pip install 'luxonis-ml[all]'` gives them.
export_requirements requirements-all.txt --no-hashes --no-default-groups --all-extras
export_requirements requirements-dev.txt --no-hashes --no-default-groups --group dev
