name: Compatibility BOM Tests

on:
  workflow_dispatch:
    inputs:
      ml_ref:
        description: 'luxonis-ml version (branch/tag/SHA)'
        required: true
        type: string
        default: main
      train_ref:
        description: 'luxonis-train version (branch/tag/SHA)'
        required: true
        type: string
        default: main
      conv_ref:
        description: 'modelconverter version (branch/tag/SHA)'
        required: true
        type: string
        default: main
      run_train:
        description: 'Run Luxonis Train tests'
        required: false
        type: boolean
        default: true
      run_converter:
        description: 'Run Modelconverter tests'
        required: false
        type: boolean
        default: true

jobs:
  test-luxonis-train:
    name: Test Luxonis Train
    if: ${{ inputs.run_train }}
    uses: Luxonis/luxonis-train/.github/workflows/tests.yaml@fix/tests-yaml # change to main when ready
    with:
      ml_ref:    ${{ inputs.ml_ref }}
      train_ref: ${{ inputs.train_ref }}
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      CODECOV_TOKEN:                  ${{ secrets.CODECOV_TOKEN }}

  test-modelconverter:
    name: Test Modelconverter
    if: ${{ inputs.run_converter }}
    uses: Luxonis/modelconverter/.github/workflows/unittests.yaml@feat/add-workflow_call-to-unittests  # change to main when ready
    with:
      ml_ref:   ${{ inputs.ml_ref }}
      conv_ref: ${{ inputs.conv_ref }}
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_ENDPOINT_URL:   ${{ secrets.AWS_S3_ENDPOINT_URL }}
      GCP_CREDENTIALS:       ${{ secrets.GCP_CREDENTIALS }}
      HUBAI_API_KEY:         ${{ secrets.HUBAI_API_KEY }}
