name: BOM Compatibility Tests

on:
  workflow_dispatch:
    inputs:
      ml_ref:
        description: 'luxonis-ml version (branch/tag/SHA)'
        required: true
        default: main
  push:

jobs:
  test-luxonis-train:
    name: Test luxonis-train
    uses: Luxonis/luxonis-train/.github/workflows/tests.yaml@fix/tests-yaml
    with:
      ml_ref: ${{ inputs.ml_ref }}
    secrets: inherit
