name: Compatibility BOM Tests

on:
  workflow_dispatch:
    inputs:
      ml_ref:
        description: 'luxonis-ml version (branch/tag/SHA)'
        required: true
        default: main
      train_ref:
        description: 'luxonis-train version (branch/tag/SHA)'
        required: true
        default: main

jobs:
  test-luxonis-train:
    uses: Luxonis/luxonis-train/.github/workflows/tests.yaml@fix/tests-yaml # Change back to main when tested
    with:
      ml_ref:    ${{ inputs.ml_ref }}
      train_ref: ${{ inputs.train_ref }}
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
