name: Compatibility BOM Tests

on:
  workflow_dispatch:
    inputs:
      ml_ref:
        description: 'luxonis-ml version (branch/tag/SHA)'
        required: true
        default: main
      train_ref:
        description: 'luxonis-train version (branch/tag/SHA)'
        required: true
        default: main
      conv_ref:
        description: 'modelconverter version (branch/tag/SHA)'
        required: true
        default: main

jobs:
  test-luxonis-train:
    name: Test Luxonis Train
    uses: Luxonis/luxonis-train/.github/workflows/tests.yaml@main
    with:
      ml_ref:    ${{ inputs.ml_ref }}
      train_ref: ${{ inputs.train_ref }}
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      CODECOV_TOKEN:                  ${{ secrets.CODECOV_TOKEN }}

  test-modelconverter:
    name: Test Modelconverter
    uses: Luxonis/modelconverter/.github/workflows/tests.yaml@feat/add-workflow_call-to-unittests
    with:
      ml_ref:   ${{ inputs.ml_ref }}
      conv_ref: ${{ inputs.train_ref }}
    secrets:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_ENDPOINT_URL:   ${{ secrets.AWS_S3_ENDPOINT_URL }}
      GCP_CREDENTIALS:       ${{ secrets.GCP_CREDENTIALS }}
      HUBAI_API_KEY:         ${{ secrets.HUBAI_API_KEY }}
