name: BOM Compatibility Tests

on:
  workflow_dispatch:
    inputs:
      ml_ref:
        description: 'luxonis-ml version (branch/tag/SHA)'
        required: true
        default: main

jobs:
  bom-tests:
    strategy:
      matrix:
        repo: ['luxonis-train']

    uses: ./downstream/${{ matrix.repo }}/.github/workflows/tests.yaml
    with:
      ml_ref: ${{ inputs.ml_ref }}
    secrets: inherit
