name: CI

on: push

jobs:
  call-reusable-workflow:
    uses: luxonis/luxonis-ml/.github/workflows/luxonis-ml-ci.yaml@27c324e
    with:
      os: 'ubuntu-latest'
      python-version: "3.8"
      src-dir: 'src/luxonis_ml'
