name: CI

on:
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'luxonis_ml/**'
      - 'tests/**'
      - .github/workflows/ci.yaml

permissions:
  pull-requests: write
  contents: write
  checks: write

jobs:
  assigner:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign
        uses: toshimaru/auto-author-assign@v2.1.1

  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Labeler
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yaml

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          pip install pydoctor
          curl -L "https://raw.githubusercontent.com/luxonis/python-api-analyzer-to-json/main/gen-docs.py" -o "gen-docs.py"

      - name: Build docs
        run: |
          python gen-docs.py luxonis_ml

  tests:
    needs:
      - pre-commit
      - docs
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.10']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install package
      run: pip install -e .[dev]

    - name: Authenticate to Google Cloud
      id: google-auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        create_credentials_file: true
        export_environment_variables: true
        token_format: access_token

    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
        LUXONISML_BUCKET: luxonis-test-bucket
      with:
        emoji: false
        custom-arguments: >
          --cov luxonis_ml
          --cov-report xml
          --junit-xml pytest.xml
        custom-pytest: pytest tests/test_nn_archive

    - name: Create Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      with:
        files: pytest.xml

    - name: Generate coverage report
      uses: orgoro/coverage@v3.1
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate coverage badge
      uses: tj-actions/coverage-badge-py@v2
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      with:
        output: coverage.svg

    - name: Upload coverage badge
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      with:
        name: coverage_badge
        path: coverage.svg

  update-coverage-badge:
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Download coverage badge
        uses: actions/download-artifact@v4
        with:
          name: coverage_badge
          path: badges/coverage.svg

      - name: Deploy Badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update coverage badge"
          branch: gh-pages
          skip_fetch: true
          skip_checkout: true

      - name: Checkout HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

