name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    uses: luxonis/luxonis-ml/.github/workflows/luxonis_ci.yaml@devops/reusable-workflow

    with:
      module: luxonis_ml
      runners: '[ "ubuntu-latest", "macos-latest", "windows-latest" ]'
      python-versions: '[ "3.8", "3.10" ]'
      main-runner: ubuntu-latest
      main-python-version: '3.10'
      docstring-format: epytext
      type-check: true
      use-labeler: true
      labeler-config: .github/labeler.yaml
      trigger: ${{ github.event_name }}

    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
