name: CI

on:
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'luxonis_ml/**'
      - 'tests/**'
      - .github/workflows/ci.yaml
      - .github/workflows/luxonis-ml-ci.yaml

jobs:
  call-reusable-workflow:
    uses: luxonis/luxonis-ml/.github/workflows/luxonis-ml-ci.yaml@feature/custom-pre-commit-hooks
    with:
      os: 'ubuntu-latest,macOS-latest,windows-latest'
      python-version: "3.8,3.10"
      src-dir: 'luxonis_ml'
