name: CI

on: pull_request

jobs:
  call-reusable-workflow:
    uses: luxonis/luxonis-ml/.github/workflows/luxonis-ml-ci.yaml@feature/custom-pre-commit-hooks
    with:
      os: 'ubuntu-latest,macOS-latest,windows-latest'
      python-version: "3.8,3.9,3.10"
      src-dir: 'src/luxonis_ml'
