name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    uses: luxonis/luxonis-ml/.github/workflows/luxonis_ci.yaml@devops/reusable-workflow

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    with:
      module: luxonis_ml
      runners: '[ "ubuntu-latest" ]'
      python-versions: '[ "3.8" ]'
      # runners: '[ "ubuntu-latest", "macos-latest", "windows-latest" ]'
      # python-versions: '[ "3.8", "3.10" ]'
      main-runner: ubuntu-latest
      main-python-version: '3.8'
      docstring-format: epytext
      type-check: false
      labeler: true
      labeler-config: .github/labeler.yaml
      semgrep: false
      trigger: ${{ github.event_name }}

  check-requirements:
    if: ${{ startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.main-python-version }}
          cache: pip

      - name: Install the package
        run: pip install -e .[all]

      - name: Check requirements
        run: |
          python3 <<EOF
          from luxonis_ml.data import *
          from luxonis_ml.utils import *
          from luxonis_ml.nn_archive import *
          EOF
