on:
  push:
    branches: [ main ]
    paths:
      - 'luxonis_ml/**'
      - 'tests/**'
jobs:
  update-base-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: coverage
        path: coverage.xml

    - name: Upload coverage results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
