name: Luxonis CI

on:
  workflow_call:
    inputs:
      runners:
        description: 'The runners to use for the matrix strategy as a JSON string'
        required: true
        type: string
      python-versions:
        description: 'The Python versions to use for the matrix strategy as a JSON string'
        required: true
        type: string
      main-runner:
        description: 'The name of the main runner'
        required: false
        type: string
        default: 'ubuntu-latest'
      main-python-version:
        description: 'The Python version of the main runner'
        required: false
        type: string
        default: '3.10'
      module:
        description: 'Name of the package to test'
        required: true
        type: string
      docstring-format:
        description: 'The format of the docstrings'
        required: false
        type: string
        default: 'restructuredtext'
      type-check:
        description: 'Whether to run type checking'
        required: false
        type: boolean
        default: false
      luxonis-ml-bucket:
        description: 'The bucket to use for LuxonisML remote storage'
        required: false
        type: string
        default: 'luxonis-test-bucket'
      use-labeler:
        description: 'Whether to use automatic labeler for PRs'
        required: false
        type: boolean
        default: false
      labeler-config:
        description: 'Path to the labeler configuration file'
        required: false
        type: string
        default: .github/labeler.yaml
      trigger:
        description: >
          The trigger for the workflow.
          Can be either "pull_request" or "push"
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: false
      GCP_CREDENTIALS:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_S3_ENDPOINT_URL:
        required: false
      ROBOFLOW_API_KEY:
        required: false

jobs:

  auto-assigner:
    if: ${{ inputs.trigger == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Auto-assign
        uses: toshimaru/auto-author-assign@v2.1.1

  labeler:
    if: ${{ inputs.use-labeler }} && ${{ inputs.trigger == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Labeler
        uses: actions/labeler@v5
        with:
          configuration-path: ${{ inputs.labeler-config }}

  pre-commit:
    if: ${{ inputs.trigger == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install pre-commit
        run: python3 -m pip install 'pre-commit<4.0.0'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  docs:
    if: ${{ inputs.trigger == 'pull_request' }}
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install pydoctor
        run: pip install pydoctor

      - name: Build docs
        run: pydoctor --docformat=${{ inputs.docstring-format }} ${{ inputs.module }}

  type-check:
    if: ${{ inputs.type-check }} && ${{ inputs.trigger == 'pull_request' }}
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          main-python-version: ${{ inputs.python-version }}
          cache: pip

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Pyright check
        uses: jakebailey/pyright-action@v2
        with:
          version: '1.1.380'
          level: warning
          warnings: true
          main-python-version: ${{ inputs.python-version }}
          project: pyproject.toml

      - name: Pyleft Check
        run: pyleft ${{ inputs.module }} --exclude __main__.py

  tests:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.runners) }}
        python-version: ${{ fromJson(inputs.python-versions) }}

    if: ${{ inputs.trigger == 'pull_request' }}
    needs:
      - pre-commit
      - type-check
    runs-on: ${{ matrix.os }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
      ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
      LUXONISML_BUCKET: ${{ inputs.luxonis-ml-bucket }}
      IS_MAIN_RUNNER: ${{ inputs.main-runner == matrix.os && inputs.main-python-version == matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          main-python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install the package
        run: pip install -e .[dev]

      - name: Authenticate to Google Cloud
        # if: ${{ secrets.GCP_CREDENTIALS }}
        id: google-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true
          token_format: access_token

      - name: Run pytest
        run: pytest --cov --junitxml=junit.xml -o junit_family=legacy -vv -x

      - name: Upload test results to Codecov
        # if: ${{ secrets.CODECOV_TOKEN }} && ${{ env.IS_MAIN_RUNNER }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Upload coverage results to Codecov
        if: ${{ secrets.CODECOV_TOKEN }} && ${{ env.IS_MAIN_RUNNER }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Upload coverage as artifact
        if: ${{ secrets.CODECOV_TOKEN }} && ${{ env.IS_MAIN_RUNNER }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          overwrite: true

  update-base-report:
    runs-on: ubuntu-latest
    if: ${{ inputs.trigger == 'push' }} && ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v7
        with:
          name: coverage
          path: coverage.xml
          workflow: luxonis_ci.yaml

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
