name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-python-publish.yaml
    with:
      uv-version: "0.11.32"
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
