name: Release Tag

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: >-
      github.event.pull_request.merged &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    uses: ./.github/workflows/reusable-release-tag.yaml
    with:
      version-file: luxonis_ml/__init__.py
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
