name: Update Coverage Report

on:
  push:
    branches: [main]

jobs:
  update-base-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.head_ref }}

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151
        with:
          name: coverage
          path: coverage.xml
          workflow: ci.yaml

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
