"""Common type aliases and utility functions for type checking."""

from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING, Any, Literal, TypeAlias, TypeGuard, TypeVar

import typeguard
from pydantic import BaseModel, ConfigDict

# When used without installed dependencies
if TYPE_CHECKING:  # pragma: no cover
    import numpy as np

    from luxonis_ml.ldf import DatasetRecord


PathType: TypeAlias = str | Path
"""A string or a `pathlib.Path`_ object.

.. _pathlib.Path:
    https://docs.python.org/3/library/pathlib.html#pathlib.Path
"""

PosixPathType: TypeAlias = str | PurePosixPath
"""A string or a `pathlib.PurePosixPath`_ object.

.. _pathlib.PurePosixPath:
    https://docs.python.org/3/library/pathlib.html#pathlib.PurePosixPath
"""

PrimitiveType: TypeAlias = str | int | float | bool | None
"""Primitive types in Python."""

# To avoid infinite recursion
if TYPE_CHECKING:  # pragma: no cover
    ParamValue: TypeAlias = (
        Mapping[str, "ParamValue"] | Sequence["ParamValue"] | PrimitiveType
    )
else:
    ParamValue: TypeAlias = Any

Params: TypeAlias = dict[str, ParamValue]
"""A keyword dictionary of additional parameters.

Usually loaded from a YAML file.
"""


class TrackedAugmentations(dict[str, Params]):
    """Augmentation provenance generated by a loader.

    A plain mapping, subclassed only to stay distinguishable from a
    record's own ``"augmentations"`` metadata.
    """


TaskType: TypeAlias = Literal[
    "classification",
    "boundingbox",
    "segmentation",
    "instance_segmentation",
    "keypoints",
    "array",
]


Labels: TypeAlias = dict[str, "np.ndarray"]
"""Dictionary mapping task names to the annotations as C{np.ndarray}"""


LoaderSingleOutput: TypeAlias = tuple["np.ndarray", Labels]
"""C{LoaderSingleOutput} is a tuple containing a single image as a
C{np.ndarray} and a dictionary of task group names and their annotations
as L{Labels}."""

LoaderMultiOutput: TypeAlias = tuple[dict[str, "np.ndarray"], Labels]
"""C{LoaderMultiOutput} is a tuple containing a dictionary mapping image
names to C{np.ndarray} and a dictionary of task group names and their
annotations as L{Labels}."""


@dataclass(slots=True)
class LoaderOutput(
    tuple[np.ndarray | dict[str, "np.ndarray"], Labels]
    if TYPE_CHECKING
    else object
):
    """Images, labels, and record metadata returned by dataset loaders.

    Prefer attribute access for new code. The object also supports the legacy
    two-value tuple protocol so existing code can continue to unpack
    ``image_or_images, labels = loader[0]``.

    Attributes:
        images: Image arrays keyed by source name. Single-source datasets use
            the conventional ``"image"`` key.
        labels: Label arrays keyed by ``"task_name/task_type"``.
        metadata: **Record-level metadata** from
            `DatasetRecord.sample_metadata`, plus any automatic loader
            metadata such as ``"filenames"`` when enabled. Augmented outputs
            also include an ``"augmentations"`` mapping from configured paths
            to the runtime parameters that were selected.
        classes: The source dataset's ``{task_name: {class_name: id}}``
            mapping, attached by `LuxonisLoader` so `to_ldf` can recover class
            names from the ids in `labels`. ``None`` for loaders that do not
            provide it.
        categorical_encodings: The source dataset's categorical metadata
            encodings, attached alongside `classes` for the same reason.

    Example:
        .. python::

            sample = loader[0]

            images = sample.images
            labels = sample.labels
            metadata = sample.metadata

            records = sample.to_ldf()  # Back to canonical LDF records.

    """

    images: dict[str, "np.ndarray"]
    labels: dict[str, "np.ndarray"]
    metadata: Params
    classes: dict[str, dict[str, int]] | None = None
    categorical_encodings: dict[str, dict[str, int]] | None = None

    def __iter__(self) -> Iterator["np.ndarray | dict[str, np.ndarray]"]:
        """Yield the legacy ``(image_or_images, labels)`` tuple shape.

        Single-source samples yield the first image array. Multi-source samples
        yield the full ``images`` mapping. Metadata is intentionally available
        only through the `metadata` attribute.
        """
        yield self.images if len(self.images) > 1 else self.image
        yield self.labels

    def __getitem__(self, index: int) -> "np.ndarray | dict[str, np.ndarray]":
        """Return legacy tuple-style values by index.

        Args:
            index: ``0`` for image data and ``1`` for labels.

        Raises:
            IndexError: If ``index`` is not ``0`` or ``1``.

        """
        if index == 0:
            return self.images if len(self.images) > 1 else self.image
        if index == 1:
            return self.labels
        raise IndexError("Index out of range. Must be 0 or 1.")

    @property
    def image(self) -> "np.ndarray":
        """Returns the first image in the images dictionary."""
        return next(iter(self.images.values()))

    def to_ldf(
        self,
        *,
        classes: dict[str, dict[str, int]] | None = None,
        categorical_encodings: dict[str, dict[str, int]] | None = None,
        render_background: bool = False,
    ) -> dict[str, "DatasetRecord"]:
        """Convert the label arrays back into canonical LDF records.

        The loader's runtime representation -- per-task numpy arrays keyed by
        ``"task_name/task_type"`` -- is rebuilt into `Detection` objects
        (pairing boxes, keypoints, instance masks, and arrays by row index)
        grouped into one `DatasetRecord` per task name. This is the inverse of
        what the loader does to a record, and is mainly useful for
        visualization.

        The records hold data that only exists in memory: `images` becomes
        their ``files`` and array labels become `ArrayAnnotation` objects
        without a path. `LuxonisDataset.add` rejects such records rather than
        storing them.

        Args:
            classes: A mapping of task name to a ``{class_name: id}`` dict,
                used to recover class names from ids. Defaults to the
                `classes` attached by the loader.
            categorical_encodings: A mapping used to decode categorical
                metadata ids back to their string values. Defaults to the
                `categorical_encodings` attached by the loader.
            render_background: Keep the semantic-segmentation background class
                as a drawable mask (named ``"background"``). When ``False``
                (the default) the background channel is dropped, mirroring how
                detection and classification treat it as a bookkeeping
                non-label.

        Returns:
            One `DatasetRecord` per task name, each holding a list of
            `Detection` objects and this sample's images.

        Raises:
            ValueError: If no class mapping is given and none was attached by
                the loader.

        Example:
            .. python::

                records = loader[0].to_ldf()

                for task_name, record in records.items():
                    for detection in record.annotation or []:
                        print(task_name, detection.class_name)

        """
        from luxonis_ml.data.loaders.label_converter import labels_to_records

        if classes is None:
            classes = self.classes
        if categorical_encodings is None:
            categorical_encodings = self.categorical_encodings
        if classes is None:
            raise ValueError(
                "Cannot convert loader output to LDF records without a class "
                "mapping. Pass `classes=dataset.get_classes()` explicitly; "
                "only outputs produced by `LuxonisLoader` carry it already."
            )
        return labels_to_records(
            self.labels,
            classes=classes,
            images=self.images,
            categorical_encodings=categorical_encodings,
            render_background=render_background,
        )


RGB: TypeAlias = tuple[int, int, int]

HSV: TypeAlias = tuple[float, float, float]

Color: TypeAlias = str | int | RGB
"""Color type alias.

Can be either a string (e.g. "red", "#FF5512"),  a tuple of RGB values,
or a single value (in which case it is interpreted as a grayscale
value).
"""


Kwargs: TypeAlias = dict[str, Any]
"""A keyword dictionary of arbitrary parameters."""


class BaseModelExtraForbid(BaseModel):
    """Base model with extra fields forbidden.

    Attributes:
        model_config: Pydantic model configuration with ``extra`` set to
            ``"forbid"``.

    """

    model_config: ConfigDict = ConfigDict(extra="forbid")


class ConfigItem(BaseModelExtraForbid):
    """Configuration schema for dynamic object instantiation. Typically
    used to instantiate objects stored in registries.

    A dictionary with a name and a dictionary of parameters.

    Attributes:
        name: Name of the object this configuration applies to.
        params: Additional parameters for instantiating the object.

    Example:
        >>> ConfigItem(name="Resize", params={"height": 256}).name
        'Resize'
        >>> ConfigItem(name="Normalize").params
        {}

    """

    name: str

    params: Params = {}


T = TypeVar("T")


def check_type(value: Any, typ: type[T]) -> TypeGuard[T]:
    """Check whether a value has the expected type.

    Note:
        This function acts as a `type guard`_, allowing type checkers
        to narrow the type of a variable when the function returns ``True``.

    Examples:
        >>> check_type("oak", str)
        True
        >>> check_type("oak", int)
        False
        >>> check_type([1, 2, 3], list)
        True

    Args:
        value: Value to check.
        typ: Type to check against.

    Returns:
        ``True`` if ``value`` conforms to ``typ``, otherwise ``False``.

    .. _type guard:
        https://typing.python.org/en/latest/spec/narrowing.html#typeguard

    """
    try:
        typeguard.check_type(value, typ)
    except (typeguard.TypeCheckError, TypeError):
        return False
    return True


def all_not_none(values: Iterable[Any]) -> bool:
    """Check whether all values in a collection are not ``None``.

    Args:
        values: Iterable of values to check.

    Returns:
        ``True`` if all values are not ``None``, otherwise ``False``.

    Examples:
        >>> all_not_none([1, "x", 0])
        True
        >>> all_not_none([1, None, 0])
        False
        >>> all_not_none([])
        True

    """
    return all(v is not None for v in values)


def any_not_none(values: Iterable[Any]) -> bool:
    """Check whether at least one value in a collection is not ``None``.

    Args:
        values: Iterable of values to check.

    Returns:
        ``True`` if at least one value is not ``None``, otherwise ``False``.

    Examples:
        >>> any_not_none([None, "x"])
        True
        >>> any_not_none([None, None])
        False
        >>> any_not_none([])
        False

    """
    return any(v is not None for v in values)
